
.ifndef _SPLASH_
    _SPLASH_ = 1

    .scope Splash

        .import splash

        .import nes86_logo
        .import energy_logo

        .import debug_string

        .import version_string

        .import copyleft_string

        .import processor_string
        .import processor_8086

        .import memory_test_string

        .import ram_string
        .import ram_pass
        .import ram_fail

        .import rom_string
        .import rom_pass
        .import rom_fail

        .import keyboard_string
        .import keyboard_on_screen
        .import keyboard_family_basic

        .import boot_string
        .import boot_count

    .endscope

.endif
